### ISSUE TITLE
Preview - ErrorMessage: certificate has expired;

### ISSUE THREAD

**Issue by wb-adegtyarev** [Frederisk/Wikitext-VSCode-Extension#41] opened 2021-12-01 07:22 UTC
The preview stopped working. Error:
`ErrorName: Error; ErrorMessage: certificate has expired;`

Wikitext: v3.6.1

**Comment by Frederisk** [comment] 2021-12-02 07:24
I checked all aspects, but this looks like [DST Root CA X3 Expiration](https://letsencrypt.org/zh-tw/docs/dst-root-ca-x3-expiration-september-2021/).🤔

**Comment by wb-adegtyarev** [comment] 2021-12-02 07:31
> I checked all aspects, but this looks like [DST Root CA X3 Expiration](https://letsencrypt.org/zh-tw/docs/dst-root-ca-x3-expiration-september-2021/).thinking
We use ISRG Root X1 certificate: https://wirenboard.com/en/

**Comment by Frederisk** [comment] 2021-12-05 04:02
I noticed that another part of the responsibility for this problem lies with electron. This problem has [an issue](https://github.com/microsoft/vscode/issues/136787) in VSCode and has been fixed in electron 16, but the repaired version of VSCode has not been released yet.

After some tests, a more interesting way to circumvent the problem is to use Linux or WSL 2 to use VSCode.

**Comment by wb-adegtyarev** [comment] 2021-12-07 07:00
> After some tests, modifying `"http.systemCertificates": false`

Thanks for the answer!
This method works. I am using Linux and Code-OSS.

**Comment by Frederisk** [comment] 2022-04-09 18:39
Fixed in VSCode v1.66.

**Closed** 2022-04-09 18:39 UTC
Labels: bug, upstream
